import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Survivor io Character Critical Rate Calculate',
  description: 'Generated by İsmail ÇAKMAK',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' container mx-auto'}>{children}</body>
    </html>
  );
}
